import icons_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Debug(object):
    def setupUi(self, Debug):
        Debug.setObjectName("Debug")
        Debug.resize(807, 615)
        Debug.setMinimumSize(QtCore.QSize(807, 580))
        Debug.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/brandp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Debug.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Debug)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("*{border: none;color:white;}#centralwidget{border-radius:5px;background-color:#fff;}#_3not,#_1not{color:black;}#codestext{border-top-right-radius:6px;border-bottom-right-radius:6px;background-color:#1e1e1e;}#helptext{color:rgb(30,30,30);}#console,#helptext{border-radius:6px;background-color:#1e1e1e;}#breakpoints{background-color:#1e1e1e;border:none;}#_2frame{border-left: 3px solid #828790;}#codeframe,#varframe,#variablestext,#cmdframe{background-color:#1e1e1e;border-radius:6px;}#main{border-right: 3px solid #828790;border-left: 3px solid #828790;}#header{border-left: 3px solid #828790;border-top: 3px solid #828790;border-right: 3px solid #828790;border-top-right-radius:5px;border-top-left-radius:5px;background:#272822;}#label,#helptext{color:white;}#helptext{padding:10px;}#footer{border-left: 3px solid #828790;border-bottom: 3px solid #828790;border-right: 3px solid #828790;border-bottom-left-radius:5px;border-bottom-right-radius:5px;}QScrollBar:vertical {border-radius: 5px;background:transparent;width:10px;margin:0px;}QScrollBar::handle:vertical {border-radius: 5px;background: #88888888;min-width:5px;max-width:5px;min-height:50px;max-height:50px;width:5px;height:5px;}QScrollBar::handle:vertical:hover {background: #888888;}QScrollBar::add-line:vertical {height: 0px;subcontrol-position: bottom;    subcontrol-origin: margin;}QScrollBar::sub-line:vertical {height: 0px;subcontrol-position: top;subcontrol-origin: margin;}QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {background:transparent;}QScrollBar:horizontal {border-radius: 5px;background:transparent;height:10px;margin:0px;}QScrollBar::handle:horizontal {border-radius: 5px;background: #88888888;min-width:50px;max-width:50px;min-height:5px;max-height:5px;width:5px;height:5px;}QScrollBar::handle:horizontal:hover {background: #888888;}QScrollBar::add-line:horizontal {height: 0px;subcontrol-position: bottom;    subcontrol-origin: margin;}QScrollBar::sub-line:horizontal {height: 0px;subcontrol-position: top;subcontrol-origin: margin;}QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {background:transparent;}QTabWidget::pane {background: #1e1e1e;border-color: #1e1e1e;border-style: solid;border-width: 0px 0px 0px 0px;border-radius:6px;color: #1e1e1e;}QTabBar::tab{height: 10px;width: 0px;border-radius:6px;}QTabWidget::tab-bar:top {top: 0px;border-radius:6px;}QTabWidget::tab-bar:bottom {bottom: 0px;border-radius:6px;}QTabWidget::tab-bar:left {right: 0px;border-radius:6px;}QTabWidget::tab-bar:right {left: 0px;border-radius:6px;}QTabBar::tab:selected {color: #1e1e1e;border-color: #1e1e1e;border-style: solid;border-radius:6px;border-width: 0px 0px 0px 0px;color: #1e1e1e;background: #1e1e1e;}QTabBar::tab:!selected {background: transparent;color: #1e1e1e;border-radius:6px;}QTabBar::tab:!selected:hover {background: #1e1e1e;color: black;border-radius:6px;}QTabBar::tab:top:last, QTabBar::tab:bottom:last,QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {margin-right: 0;border-radius:6px;}QTabBar::tab:left:last, QTabBar::tab:right:last,QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {margin-bottom: 0;border-radius:6px;}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainMenu = QtWidgets.QFrame(self.centralwidget)
        self.mainMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainMenu.setSizeIncrement(QtCore.QSize(-10205, 0))
        self.mainMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.mainMenu)
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 6, 4, 6)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.header)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/pyfile.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.header)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.downBut = QtWidgets.QPushButton(self.frame_3)
        self.downBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/Zmin1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downBut.setIcon(icon2)
        self.downBut.setObjectName("downBut")
        self.horizontalLayout_4.addWidget(self.downBut)
        self.minimize = QtWidgets.QPushButton(self.frame_3)
        self.minimize.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/Zres2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize.setIcon(icon3)
        self.minimize.setIconSize(QtCore.QSize(20, 20))
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_4.addWidget(self.minimize)
        self.closeBut = QtWidgets.QPushButton(self.frame_3)
        self.closeBut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Zx1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBut.setIcon(icon4)
        self.closeBut.setIconSize(QtCore.QSize(20, 20))
        self.closeBut.setObjectName("closeBut")
        self.horizontalLayout_4.addWidget(self.closeBut)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.header)
        self.main = QtWidgets.QFrame(self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMinimumSize(QtCore.QSize(807, 510))
        self.main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.helpframe = QtWidgets.QFrame(self.main)
        self.helpframe.setMaximumSize(QtCore.QSize(0, 16777215))
        self.helpframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.helpframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.helpframe.setObjectName("helpframe")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.helpframe)
        self.verticalLayout_3.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.helptext = QtWidgets.QLabel(self.helpframe)
        self.helptext.setMinimumSize(QtCore.QSize(220, 0))
        self.helptext.setWordWrap(True)
        self.helptext.setObjectName("helptext")
        self.verticalLayout_3.addWidget(self.helptext, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_11.addWidget(self.helpframe)
        self.frame_5 = QtWidgets.QFrame(self.main)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.secnames = QtWidgets.QFrame(self.frame_5)
        self.secnames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.secnames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.secnames.setObjectName("secnames")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.secnames)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame = QtWidgets.QFrame(self.secnames)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self._3not = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self._3not.setFont(font)
        self._3not.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._3not.setIndent(8)
        self._3not.setObjectName("_3not")
        self.horizontalLayout_16.addWidget(self._3not)
        self._4imp = QtWidgets.QLabel(self.frame)
        self._4imp.setMaximumSize(QtCore.QSize(40, 40))
        self._4imp.setText("")
        self._4imp.setPixmap(QtGui.QPixmap(":/icons/icons/pyfile.svg"))
        self._4imp.setScaledContents(True)
        self._4imp.setObjectName("_4imp")
        self.horizontalLayout_16.addWidget(self._4imp)
        self.horizontalLayout_17.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(self.secnames)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self._1not = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self._1not.setFont(font)
        self._1not.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._1not.setIndent(8)
        self._1not.setObjectName("_1not")
        self.horizontalLayout_15.addWidget(self._1not)
        self._2imp = QtWidgets.QLabel(self.frame_7)
        self._2imp.setMaximumSize(QtCore.QSize(40, 40))
        self._2imp.setText("")
        self._2imp.setPixmap(QtGui.QPixmap(":/icons/icons/4215538.png"))
        self._2imp.setScaledContents(True)
        self._2imp.setObjectName("_2imp")
        self.horizontalLayout_15.addWidget(self._2imp)
        self.horizontalLayout_17.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.secnames)
        self.general = QtWidgets.QFrame(self.frame_5)
        self.general.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general.setFrameShadow(QtWidgets.QFrame.Raised)
        self.general.setObjectName("general")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.general)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.codeframe = QtWidgets.QFrame(self.general)
        self.codeframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.codeframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.codeframe.setObjectName("codeframe")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.codeframe)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.codeframe)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout_8.addWidget(self.tabWidget)
        self.horizontalLayout_12.addWidget(self.codeframe)
        self.varframe = QtWidgets.QFrame(self.general)
        self.varframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.varframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.varframe.setObjectName("varframe")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.varframe)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.variablestext = QtWidgets.QTextEdit(self.varframe)
        self.variablestext.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.variablestext.setObjectName("variablestext")
        self.horizontalLayout_13.addWidget(self.variablestext)
        self.horizontalLayout_12.addWidget(self.varframe)
        self.verticalLayout_2.addWidget(self.general)
        self.button_group = QtWidgets.QFrame(self.frame_5)
        self.button_group.setMaximumSize(QtCore.QSize(16777215, 40))
        self.button_group.setStyleSheet("QPushButton{border:1 px solid #0d6efd;background-color:#0d6efd;color:rgb(255,255,255);font: 700 12pt \"Segoe UI\";}QPushButton:hover{background-color:#0b5ed7;}#button_step{border-top-left-radius:6px;border-bottom-left-radius:6px;}#button_help{border-top-right-radius:6px;border-bottom-right-radius:6px;}")
        self.button_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_group.setObjectName("button_group")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.button_group)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.button_step = QtWidgets.QPushButton(self.button_group)
        self.button_step.setMinimumSize(QtCore.QSize(70, 35))
        self.button_step.setMaximumSize(QtCore.QSize(70, 35))
        self.button_step.setObjectName("button_step")
        self.horizontalLayout_10.addWidget(self.button_step)
        self.button_next = QtWidgets.QPushButton(self.button_group)
        self.button_next.setMinimumSize(QtCore.QSize(70, 35))
        self.button_next.setMaximumSize(QtCore.QSize(70, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.button_next.setFont(font)
        self.button_next.setObjectName("button_next")
        self.horizontalLayout_10.addWidget(self.button_next)
        self.button_return = QtWidgets.QPushButton(self.button_group)
        self.button_return.setMinimumSize(QtCore.QSize(70, 35))
        self.button_return.setMaximumSize(QtCore.QSize(70, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.button_return.setFont(font)
        self.button_return.setObjectName("button_return")
        self.horizontalLayout_10.addWidget(self.button_return)
        self.button_continue = QtWidgets.QPushButton(self.button_group)
        self.button_continue.setMinimumSize(QtCore.QSize(80, 35))
        self.button_continue.setMaximumSize(QtCore.QSize(80, 35))
        self.button_continue.setObjectName("button_continue")
        self.horizontalLayout_10.addWidget(self.button_continue)
        self.button_help = QtWidgets.QPushButton(self.button_group)
        self.button_help.setMinimumSize(QtCore.QSize(35, 35))
        self.button_help.setMaximumSize(QtCore.QSize(35, 35))
        self.button_help.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_help.setIcon(icon5)
        self.button_help.setIconSize(QtCore.QSize(35, 35))
        self.button_help.setObjectName("button_help")
        self.horizontalLayout_10.addWidget(self.button_help)
        self.verticalLayout_2.addWidget(self.button_group, 0, QtCore.Qt.AlignHCenter)
        self.cmdframe = QtWidgets.QFrame(self.frame_5)
        self.cmdframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cmdframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cmdframe.setObjectName("cmdframe")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.cmdframe)
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_2.addWidget(self.cmdframe)
        self.horizontalLayout_11.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.main)
        self.footer = QtWidgets.QFrame(self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer.sizePolicy().hasHeightForWidth())
        self.footer.setSizePolicy(sizePolicy)
        self.footer.setMinimumSize(QtCore.QSize(0, 20))
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(786, 15))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.sizeGrip = QtWidgets.QFrame(self.footer)
        self.sizeGrip.setMinimumSize(QtCore.QSize(15, 15))
        self.sizeGrip.setMaximumSize(QtCore.QSize(15, 15))
        self.sizeGrip.setObjectName("sizeGrip")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.sizeGrip)
        self.horizontalLayout_5.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sizegrip = QtWidgets.QPushButton(self.sizeGrip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizegrip.sizePolicy().hasHeightForWidth())
        self.sizegrip.setSizePolicy(sizePolicy)
        self.sizegrip.setMinimumSize(QtCore.QSize(12, 12))
        self.sizegrip.setMaximumSize(QtCore.QSize(12, 12))
        self.sizegrip.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/grid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sizegrip.setIcon(icon6)
        self.sizegrip.setIconSize(QtCore.QSize(12, 12))
        self.sizegrip.setObjectName("sizegrip")
        self.horizontalLayout_5.addWidget(self.sizegrip)
        self.horizontalLayout_3.addWidget(self.sizeGrip, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.footer)
        self.horizontalLayout.addWidget(self.mainMenu)
        Debug.setCentralWidget(self.centralwidget)

        self.retranslateUi(Debug)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Debug)

    def retranslateUi(self, Debug):
        _translate = QtCore.QCoreApplication.translate
        Debug.setWindowTitle(_translate("Debug", "Debugger"))
        self.label.setText(_translate("Debug", "PyNar Hata Ayıklayıcı"))
        self.helptext.setText(_translate("Debug", "<html>\n"
"  <head></head>\n"
"  <body>\n"
"    <h2>Yardım</h2>\n"
"    <ul>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Step</span>\n"
"        <span> Mevcut seviyede kalarak bir sonraki satıra geçin.</span>\n"
"      </li>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Next</span>\n"
"        <span> Bir sonraki satıra geçin ve varsa bir işleve geçin.</span>\n"
"      </li>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Return</span>\n"
"        <span> Geçerli işlevden çıkın.</span>\n"
"      </li>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Continue</span>\n"
"        <span>Yürütmeye devam edin.</span>\n"
"      </li>\n"
"        <li>\n"
"          <span style=\"font-weight: 700; color: #ff0000\">Kesme Noktası</span>\n"
"          <span style=\"font-weight: 700; color: #0000ff\"> eklemek</span>\n"
"          <span>için konsol kutusuna b yazıp eklemek istediğiniz satırın numarasını yazın.(örn: b 8 )(8.satıra kesme noktası ekler).</span>\n"
"        </li>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Kesme Noktası</span>\n"
"        <span style=\"font-weight: 700; color: #0000ff\"> kaldırmak</span>\n"
"        <span>için konsol kutusuna cl yazıp kaldırmak istediğiniz kesme noktası\n"
"          kaçıncı sıradaysa onu yazınız.(örn: cl 3)(üçüncü eklenen kesme\n"
"          noktasını kaldırır).</span>\n"
"      </li>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Kesme Noktası</span>\n"
"        <span style=\"font-weight: 700; color: #0000ff\"> eklemek</span>\n"
"        <span>için Çalıştırılan dosya kutusundaki satır numaralarının sağına tıklayınız.</span>\n"
"      </li>\n"
"      <li>\n"
"        <span style=\"font-weight: 700; color: #ff0000\">Kesme Noktası</span>\n"
"        <span style=\"font-weight: 700; color: #0000ff\"> kaldırmak</span>\n"
"        <span>için Çalıştırılan dosya kutusundaki daha önce eklenmiş Kesme noktasına tıklayarak kaldırabilirsiniz.</span>\n"
"      </li>\n"
"    </ul>\n"
"  </body>\n"
"</html>\n"
""))
        self._3not.setText(_translate("Debug", "Çalıştırılan Dosya"))
        self._1not.setText(_translate("Debug", "Değişkenler"))
        self.button_step.setToolTip(_translate("Debug", "<html><head/><body><p><span style=\" color:#0d6efd;\">Mevcut seviyede kalarak bir sonraki satıra geçin. </span></p></body></html>"))
        self.button_step.setText(_translate("Debug", "Step"))
        self.button_next.setToolTip(_translate("Debug", "<html><head/><body><p><span style=\" color:#0d6efd;\">Bir sonraki satıra geçin ve varsa bir işleve geçin.  </span></p></body></html>"))
        self.button_next.setText(_translate("Debug", "Next"))
        self.button_return.setToolTip(_translate("Debug", "<html><head/><body><p><span style=\" color:#0d6efd;\">Geçerli işlevden çıkın.</span></p></body></html>"))
        self.button_return.setText(_translate("Debug", "Return"))
        self.button_continue.setToolTip(_translate("Debug", "<html><head/><body><p><span style=\" color:#0d6efd;\">Yürütmeye devam edin.</span></p></body></html>"))
        self.button_continue.setText(_translate("Debug", "Continue"))
        self.button_help.setToolTip(_translate("Debug", "<html><head/><body><p><span style=\" color:#0d6efd;\">Yardım Menüsü.</span></p></body></html>"))
